// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsh1P1L4xUCa27IdDJoR9DWlOpHaJf4Uk',
    appId: '1:160635759571:web:8e772fc2990d36f0c39d26',
    messagingSenderId: '160635759571',
    projectId: 'seeds-bits',
    authDomain: 'seeds-bits.firebaseapp.com',
    storageBucket: 'seeds-bits.firebasestorage.app',
    measurementId: 'G-PFEZDRMP5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0WdmH0_PUSl4EESF_5uNz8SU701hkbqU',
    appId: '1:160635759571:android:18019c219f3c9ef6c39d26',
    messagingSenderId: '160635759571',
    projectId: 'seeds-bits',
    storageBucket: 'seeds-bits.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsh1P1L4xUCa27IdDJoR9DWlOpHaJf4Uk',
    appId: '1:160635759571:web:c4a70c407c7afcf0c39d26',
    messagingSenderId: '160635759571',
    projectId: 'seeds-bits',
    authDomain: 'seeds-bits.firebaseapp.com',
    storageBucket: 'seeds-bits.firebasestorage.app',
    measurementId: 'G-T37CV2WR0F',
  );
}
